name: Upload Website

on:
  push:
    branches:
      - main
    paths:
      - frontend/**/*

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: AKIA6CLGK5NGYKJHBWND
      AWS_SECRET_ACCESS_KEY: 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

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          cache-dependency-path: './frontend/yarn.lock'

      - name: Build
        working-directory: './frontend'
        run: |
          yarn
          yarn build

      - name: Push into S3
        uses: reggionick/s3-deploy@v3
        with:
          folder: frontend/dist
          bucket: gic-codetoimpact-team04-fe
          bucket-region: ap-southeast-1
